language: android
jdk: oraclejdk8
sudo: false
env:
    - GRADLE_OPTS='-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

machine:
   environment:
     GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    # Uncomment this if you need emulator
    # - sys-img-x86-android-23
  licenses:
    - 'android-sdk-license-.+'

before_install:
    - export TERM=dumb
    - chmod +x gradlew

# Uncomment this if you need emulator
# before_script:
#  - echo no | android create avd --force -n test -t android-21 --abi x86
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

script:
    - ./gradlew checkstyle lintProductionRelease testProductionReleaseUnitTest

branches:
  only:
    - master
    - production

# after_success: uncomment this and add your own deployment targets